spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url : jdbc:mariadb://localhost:3307/togeball
    url: jdbc:mariadb://i10a610.p.ssafy.io:3306/togeball
    username: root
    password: ssafy
  config:
    import: optional:properties/jpa.yml

jwt:
  secretKey: eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaiwrdOoPcAKmUzNa1srrRfxZVGL
  access:
    expiration: 3600000 # 3600000 : 60(분) * 60(초) * 1000 -> 1 시간
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh
